"""Unit tests for the single-pass large-PR digest pass.

No network: the digest pool is FakeExec-backed, so these pin the wiring deterministically — the
single resilient Pool.run (with failover), the fail-loud oversize guard, rotation order, and the
render/log shapes.
"""

from __future__ import annotations

import asyncio
import json
from datetime import UTC, datetime

from agents.pr_review_ensemble.config import settings
from agents.pr_review_ensemble.digest import build_digest_pool, run_digest
from agents.pr_review_ensemble.logger import log_digest
from agents.pr_review_ensemble.models import DigestResult
from agents.pr_review_ensemble.providers import ReviewerSlot, SkipExecutor
from agents.pr_review_ensemble.renderer import render_digest
from agents.shared.ensemble import ExecResult, ExecStatus, FailureClass, Pool, Prompt


class FakeExec:
    def __init__(
        self,
        label: str,
        *,
        status: ExecStatus = ExecStatus.OK,
        output: str = "# Digest\nbody",
        error: str | None = None,
        fc: FailureClass = FailureClass.NONE,
        boom: bool = False,
    ) -> None:
        self.label = label
        self._r = ExecResult(
            executor=label,
            status=status,
            output=output,
            error=error,
            failure_class=fc,
            latency_ms=1,
        )
        self._boom = boom
        self.called = False

    async def run(self, prompt: Prompt, *, timeout: float) -> ExecResult:
        self.called = True
        if self._boom:
            raise AssertionError("executor should not have been called")
        return self._r.model_copy()


def _pool(*execs: FakeExec) -> Pool:
    return Pool(role="digest", executors=list(execs))


def _slot(provider: str, *, active: bool = True) -> ReviewerSlot:
    ex = FakeExec(f"{provider}:m") if active else SkipExecutor(f"{provider}:m", "skip")
    return ReviewerSlot(
        provider=provider,
        model="m",
        pool=Pool(role=f"review:{provider}", executors=[ex]),
        skipped_reason=None if active else "skip",
    )


def _run(diff="a\nb\n", pr="PR", pool=None, slots=None):
    return asyncio.run(run_digest(diff_text=diff, pr_ref=pr, pool=pool, slots=slots))


def test_digest_success():
    res = _run(pool=_pool(FakeExec("local:coder", output="# Digest\nhello")))
    assert res.digest == "# Digest\nhello"
    assert res.model == "local:coder"
    assert res.error is None and not res.oversize


def test_digest_fails_over_to_next():
    first = FakeExec(
        "anthropic:x", status=ExecStatus.ERROR, output="", error="down", fc=FailureClass.TERMINAL
    )
    second = FakeExec("local:coder", output="# Digest\nok")
    res = _run(pool=_pool(first, second))
    assert res.digest == "# Digest\nok"
    assert res.model == "local:coder"  # failed over from the first


def test_digest_all_fail():
    pool = _pool(
        FakeExec("a:x", status=ExecStatus.ERROR, output="", error="boom", fc=FailureClass.TERMINAL)
    )
    res = _run(pool=pool)
    assert res.digest is None
    assert res.error is not None


def test_digest_oversize_short_circuits(monkeypatch):
    monkeypatch.setattr(settings, "digest_max_diff_chars", 5)
    boom = FakeExec("local:coder", boom=True)
    res = _run(diff="x" * 50, pool=_pool(boom))
    assert res.oversize is True
    assert res.digest is None
    assert "over the single-pass budget" in (res.error or "")
    assert boom.called is False  # never attempted — guard short-circuits before the pool


def test_digest_empty_pool():
    res = _run(pool=Pool(role="digest", executors=[]))
    assert res.digest is None
    assert "no active providers" in (res.error or "")


def test_build_digest_pool_rotation_excludes_inactive(monkeypatch):
    monkeypatch.setattr(
        settings, "aggregator_provider", "anthropic"
    )  # preferred, but inactive here
    slots = [_slot("anthropic", active=False), _slot("local"), _slot("opencode_zen")]
    pool = build_digest_pool(slots)
    assert [e.label for e in pool.executors] == ["opencode_zen:m", "local:m"]


def _result(**kw) -> DigestResult:
    base = dict(pr_ref="PR", timestamp=datetime.now(UTC), diff_lines=10, diff_chars=100)
    base.update(kw)
    return DigestResult(**base)


def test_render_digest_success():
    md = render_digest(_result(digest="# D\nbody", model="local:coder"))
    assert "# PR Digest: PR" in md
    assert "**Generated by:** local:coder" in md
    assert "body" in md


def test_render_digest_oversize():
    md = render_digest(_result(oversize=True, error="diff too big"))
    assert "too large for single-pass" in md.lower()
    assert "diff too big" in md


def test_log_digest(tmp_path):
    res = _result(digest="x" * 20, model="local:coder")
    path = tmp_path / "runs.jsonl"
    log_digest(res, log_path=path)
    rec = json.loads(path.read_text(encoding="utf-8").strip())
    assert rec["pass"] == "digest"
    assert rec["ok"] is True
    assert rec["model"] == "local:coder"
    assert rec["digest_chars"] == 20
